version: '2'
services:
  vscode:
    build: .
    network_mode: bridge
    restart: unless-stopped
    privileged: true
    volumes:
      - .:/home/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    ports:
      - 3333:3000
    expose:
      - 3000
  
  vscode-basic-auth-proxy:
    image: ipepe/nginx-basic-auth # https://github.com/ipepe-oss/nginx-basic-auth-proxy
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 3001:80
      - 3443:443
      - 8090:8090
    expose:
      - 80
    environment:
      PROXY_PASS: http://vscode:3000
      BASIC_AUTH_USERNAME: admin
      BASIC_AUTH_PASSWORD: admin
    links:
      - vscode
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:code.ipepe.pl"

  postgres_db:
    network_mode: bridge
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: Password1
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/dbdumps:/dbdumps
